# Generated by Django 5.0.14 on 2026-06-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('screen_type', models.CharField(choices=[('2D', 'Standard 2D'), ('3D', 'Standard 3D'), ('IMAX', 'IMAX 3D')], default='2D', max_length=10, verbose_name='Тип экрана')),
                ('rows', models.IntegerField(verbose_name='Количество рядов')),
                ('cols', models.IntegerField(verbose_name='Количество мест в ряду')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Длительность (мин)')),
                ('poster', models.CharField(max_length=500, verbose_name='Ссылка на постер')),
                ('banner', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на баннер')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг Кинопоиск/IMDb')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режиссер')),
                ('release_date', models.DateField(verbose_name='Дата премьеры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('number', models.IntegerField(verbose_name='Место')),
                ('category', models.CharField(choices=[('STANDARD', 'Стандартное'), ('VIP', 'VIP (Комфорт)'), ('LOVESEAT', 'Love Seat (Двойное)')], default='STANDARD', max_length=20, verbose_name='Категория')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.hall', verbose_name='Кинозал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bookings.hall', verbose_name='Кинозал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bookings.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking', verbose_name='Бронирование')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.seat', verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row', 'number'), name='unique_hall_seat'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='unique_session_seat'),
        ),
    ]
